### ISSUE TITLE
Harden GitHub Actions

### ISSUE THREAD

**Issue by demisx** [frequency-chain/frequency#1152]
GitHub Actions provide powerful and easy-to-access features to build automation right into any GitHub repository. However, they also require special attention to avoid any compromise. Research and implment best practices to secure them.

**References**:
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
- https://blog.gitguardian.com/github-actions-security-cheat-sheet/
- https://engineering.salesforce.com/github-actions-security-best-practices-b8f9df5c75f5/

**Comment by wilwade** [comment]
Closing for now with the use of allowlisted actions
