### ISSUE TITLE
Support DinD mode on EKS Runners

### ISSUE THREAD

**Issue by demisx** [frequency-chain/frequency#1543]
This may resolve issue with job running docker that currently fail on the official Ubuntu image.

References:
- https://hub.docker.com/r/dcagatay/ubuntu-dind
- https://github.com/cruizba/ubuntu-dind
- https://github.com/teracyhq/docker-files/tree/master/ubuntu
- [Official Docker DIND images](https://hub.docker.com/_/docker)
- [Deploying alternative runners](https://github.com/actions/actions-runner-controller/blob/master/docs/deploying-alternative-runners.md#runner-with-dind)

**Comment by wilwade** [comment]
That looks good to me.

**Comment by wilwade** [comment]
Closing as not needed for now
