### ISSUE TITLE
Add Zombie-net 

### ISSUE THREAD

**Issue by mattheworris** [frequency-chain/frequency#1749]
### Title:
Add the ability to use Zombie net for relay network testing.

### Description:
Implementation will include:

1. A `frequency-network.toml` network setup used to create the test relay network. It will contain two validators, alice and bob.
2. Polkadot binaries: either the polkadot binaries will be commited, or otherwise pulled from a public repo.
3. Makefile will be update to execute the zombie-net commands.
4. Zombie-net binaries may be needed for your local system. Investigation as to whether or not we can build them in-situ may be done.

### Acceptance Criteria:
- [ ]  Instructions should be correct and general enough for most users and most systems.
- [ ] Makefile commands should execute correctly.
- [ ] ?

### Ethical Considerations:
I am not aware of any ways that adding zombie net testing would impact ethical considerations.

Checklist:
- [ ] All acceptance criteria are met
- [ ] Code has been reviewed by at least one team member
- [ ] Code has been tested thoroughly and no new issues have been introduced
- [ ] Documentation has been updated (if applicable)
- [ ] Any necessary configuration changes have been made
- [ ] Changes have been merged into the appropriate branch
- [ ] Changes have been deployed to the appropriate environment (if applicable)

**Comment by wilwade** [comment]
Closing as not needed for now.
