### ISSUE TITLE
`target_hash` RPC Level validation

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#1860]
As someone transacting using stateful storage, I want to have my transaction stopped at the node level if I submit something with a bad `target_hash` so that I don't waste capacity on a transaction that will fail.

## Scenario
- User has two providers, A and B
- User is actively using both A and B
- User makes a change on A and a change on B that both effect the same stateful store
- Provider A makes the change
- Provider B uses the cached value from before the change by A
- The changes are in a race condition
- Provider B would like to safely use the cached value without fear of an invalid hash using capacity

## Checklist
- [ ] Make sure the pallet benchmarks are correct
- [ ] Make sure the overhead benchmarks are correct

## Questions
- Should this validation run on `pre_dispatch` as well as `validate`?
    - **A**: We want to do both 
    - If `pre_dispatch` and `validate`, we should remove the check in the extrinsic
    - If just `validate`, we cannot remove the extrinsic check, but also no weights etc...
- Should other checks also be moved into the signed extrinsics?
    - Just the one check for the hash

Draft PR: https://github.com/LibertyDSNP/frequency/pull/1288

**Comment by JoeCap08055** [comment]
I think one question to answer is: is it possible to read only the first N bytes of a page? I hate to have to read the entire page in the signed extension when we only care about the page hash in the first few bytes of the page storage for each page.

**Comment by saraswatpuneet** [comment]
Few things we can check if possible

* Hash 
* MSAid/delegation ( not important as we check in services side of user is delegated of not but nice to have )
* Check for correctness of provided SchemaId

**Comment by enddynayn** [comment]
can you please remind me how someone might gat a bad_hash?

**Comment by saraswatpuneet** [comment]
Should we provide an RPC to validate a hash ? That way we can check for correctness of hash at the time of computing it via graphsdk

Advantage: we can proactively make sure only valid hashes are being sent to chain then wait for chain to tell us it's bad ?

**Comment by aramikm** [comment]
Our RPC returns current hash once a page is retrieved. Not sure if we need an additional RPC.

**Comment by saraswatpuneet** [comment]
Is there a way to know with the above info if a give hash is stale or not ?

**Comment by aramikm** [comment]
> I think one question to answer is: is it possible to read only the first N bytes of a page? I hate to have to read the entire page in the signed extension when we only care about the page hash in the first few bytes of the page storage for each page.

Not possible. Accessing the node is the heavier side of the operation compared to deserialization to the type.

> Is there a way to know with the above info if a given hash is stale or not ?

RPC only returns the data already stored on blockchain (so it might not be finalized but we have this problem in everywhere and also it does not consider anything in the transaction pool). So from RPC standpoint it only return the valid hash at the exact time asked but then it might not be accurate for T + 1 but we can't do much about it.


My recommendation is that we do not change the extrinsic implementations and only add following checks in **pre_dispatch** to provide fail fast feature without adding any overhead on the whole network.

- Check hash staleness
- Check Schema validity

**Comment by wilwade** [comment]
> My recommendation is that we do not change the extrinsic implementations and only add following checks in **pre_dispatch** to provide fail fast feature without adding any overhead on the whole network.
> 
>     * Check hash staleness
>     * Check Schema validity

I like this. Simple and provides the number one thing we are missing: RPC safety.

**Comment by enddynayn** [comment]
>If just validate, we cannot remove the extrinsic check, but also no weights etc...
@wilwade 
It is not good practice to add something to validate and not pre-dispatch. Your pre-dispatch must call your validation.

**Comment by JoeCap08055** [comment]
> My recommendation is that we do not change the extrinsic implementations and only add following checks in **pre_dispatch** to provide fail fast feature without adding any overhead on the whole network.
> 
> * Check hash staleness
> * Check Schema validity

I disagree with "Check schema validity". We have plenty of extrinsics that check schema validity; what's the argument for checking only this one in pre_dispatch? Content hash is a special case unique to stateful storage, and the potential for a rejected call is outside the control of the caller. A bad schema ID is entirely the fault of the caller and within their control to prevent; no need to add a schema and/or delegation read to the pre_dispatch as well.

**Comment by wilwade** [comment]
> It is not good practice to not call your validate function in pre-dispatch. Your pre-dispatch must call your validation function.
> Additionally, we would need to run the overhead benchmarks for this. This implies that all our transactions include this additional weight.

@enddynayn I agree that this is uncommon, but I think this is a great example of a place to do it. We have a validation in the extrinsic that is (from my understanding) expensive to extract to `validate`. Assuming that is true, this is a great use case of just blocking honest RPCs from causing unneeded bad transactions to be gossiped.

The danger would be if someone thinks it is enough to just do the `pre_dispatch`. However, in this case the setup would be clear that this is just a helper for honest actors.

That said @aramikm, if the worry is that we have to add a database read, I don't think this is so. The caching layer would cache the first read in `validate` and then it would have a cache hit on the second read in the extrinsic. Or perhaps I am missing a piece?

**Comment by enddynayn** [comment]
@wilwade I thought we wanted to prevent this from getting in the block and using capacity. I guess I am unclear about the problem we are trying to solve.

**Comment by wilwade** [comment]
I believe all the questions have been resolved and the details are now in the issue description. If this is incorrect, please post the list of open questions.

**Comment by JoeCap08055** [comment]
> ## Questions
> * Should this validation run on `pre_dispatch` as well as `validate`?
>   
>   * **A**: We want to do both
>   * If `pre_dispatch` and `validate`, we should remove the check in the extrinsic

I don't think it would cost anything to keep the `target_hash` check in the extrinsic as well, as long as we're reading the storage anyway. At that point it only costs a string comparison.

**Comment by aramikm** [comment]
We deployed reverted this but not sure why it's in a blocked state

**Comment by wilwade** [comment]
@aramikm I I think I stuck it there as a way to remember to re-evaluate if we wanted to un-revert it (in some way at least).
