### ISSUE TITLE
Schema Creation should Reject `SignatureRequired` for OnChain and IPFS Payload Locations

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#1874]
Currently it is possible to create a schema with the setting `SignatureRequired` when also using the `PayloadLocation` of `OnChain` or `IPFS`.

Expected: Schema creation and proposal for creation should reject a schema setting that does not apply to the selected `PayloadLocation`

As a developer creating a schema (or someone reading a schema), I want to make sure that I do not incorrectly think that the `SignatureRequired` will do something for Message Storage based schemas, when it does not.

**Comment by JoeCap08055** [comment]
Would there be any benefit to adding support for `SignatureRequired` to other pallets besides `StatefulStorage`?

**Comment by wilwade** [comment]
> Would there be any benefit to adding support for `SignatureRequired` to other pallets besides `StatefulStorage`?

`IPFS` doesn't have a delegation option, as it assumes the off-chain data handles any delegation interaction.

I think there might be for `OnChain`, but no clear use case at this point in time.

**Comment by JoeCap08055** [comment]
I also think that for schemas with `SignatureRequired`, we should explicitly reject any delegation requests for that schema.

**Comment by wilwade** [comment]
> I also think that for schemas with `SignatureRequired`, we should explicitly reject any delegation requests for that schema.

Hmm... That sounds good, but it requires a load of a lot of data when doing a delegation to check for that flag on schemas. Open to ideas of how to do it for opening a separate issue however.
