### ISSUE TITLE
Remove `nightly` from `cargo doc` commands

### ISSUE THREAD

**Issue by mattheworris** [frequency-chain/frequency#1909]
Using `export RUSTC_BOOTSTRAP=1` turns your stable rustc into a Nightly one.

For `cargo` commands that rely on `rustc` and use `unstable` options, `+nightly` can be removed in favor of `RUSTC_BOOTSTRAP=1`.

This will reduce dependence on `nightly`.

Further evaluation for removing `nightly`: updating `.rustfmt.toml` to remove all unstable features as listed in #1895 could eliminate `nightly` dependence.

**Comment by wilwade** [comment]
Fixed by #2120
