### ISSUE TITLE
Can't create raw build spec, Getting error Unknown chain identity

### ISSUE THREAD

**Issue by shanithkk** [frequency-chain/frequency#1925]
### Description
When i trying to build the raw build spec from plain build spec, getting an error like 
` thread 'main' panicked at node/cli/src/command.rs:44:13:
Unknown chain identity 
`

### Expected behaviour 
Should build the raw spec from the given plain spec 

### Steps to reproduce

1. Create plain spec 
    `/frequency/target/release/frequency build-spec --chain=frequency-rococo-local --disable-default-bootnode >/tmp/frequency-rococo.json`
2. Build the raw build spec
   `/frequency/target/release/frequency build-spec --chain=/tmp/frequency-rococo.json --raw --disable-default-bootnode > /tmp/fre-raw.json`

**Comment by saraswatpuneet** [comment]
@shanithkk there is a type `--chain=frequency-rococ-local` -> `--chain=frequency-rococo-local`

**Comment by shanithkk** [comment]
@saraswatpuneet its my bad, actually i ran correct command only
<img width="923" alt="Screenshot 2024-03-26 at 10 13 54 PM" src="https://github.com/LibertyDSNP/frequency/assets/59169878/535eefcc-e1f1-46ea-a490-7d98b8ee203a">

Highlighted. i thing the issue coming due to the chain spec id

**Comment by wilwade** [comment]
@shanithkk Two things that might be the issue.

1. The change identity changed with the recent update to support the Paseo testnet. `frequency-local` is the chain value you want to use now for a local run (be it `paseo-local` or `rococo-local`)
2. We limit the chain support depending on the build features. You want to be using `cargo build --features frequency-local` or if you prefer the release build `cargo build --release --features frequency-local` (While it can cause confusion like this, it means testcode and production code more more separated)

**Comment by wilwade** [comment]
Closing as stale. Feel free to reopen.
