### ISSUE TITLE
[Chore]:  DB r/w optimizations for ProviderBoost operations

### ISSUE THREAD

**Issue by shannonwells** [frequency-chain/frequency#1967]
# Problem
The results of the benchmarks for Capacity's `provider_boost` and `on_initialize` show that there is a need to try to get this down as much as possible.

The worst case `on_initialize` total weights increased by over 4X, and the `provider_boost` extrinsic cost is 2nd or 3rd highest of all the extrinics.

See PR #1966

**Comment by wilwade** [comment]
Closed in part by #2005
