### ISSUE TITLE
[Feature]: Capacity Pallet: Use Relay Chain block number instead of Frequency

### ISSUE THREAD

**Issue by enddynayn** [frequency-chain/frequency#1987]
**Description**
The Polkadot community advises parachains to avoid using the block number as a clock. This recommendation is due to features like asynchronous backing and agile core time, as well as potential future optimizations, which could impair the reliability of using the block number as a timekeeping mechanism.

[reference](https://github.com/paritytech/polkadot-sdk/pull/1761)

**Comment by wilwade** [comment]
# Community Call Notes 2024-09-19

- How much is the drift?
   - Currently not much, but could in the future

**Comment by wilwade** [comment]
# Community Call Notes 2024-10-17

- Not something to do at this time
