### ISSUE TITLE
[Design doc] P256 Signature Proxy Support

### ISSUE THREAD

**Issue by p5150j** [frequency-chain/frequency#1999]
We need to get a design doc started for Passkey support. This should follow the other design doc patterns.

Additions to design doc needed 

-  need a data flow diagram
-  need a data map for legal teams 
- .....

Design Doc Readme and Template: https://github.com/LibertyDSNP/meta/blob/main/DESIGN_DOCS.md

## Design Doc Needs

- [x] Data flow diagram
    - [x] What information is stored and accessible where
- [x] Terminology
    - [x] Different Keys
    - [x] Signature Proxy Pallet?
- [x] Why section
    - [x] Ease of user using tokens
    - [x] Options for backup and recovery
    - [x] etc...
- [x] Spec on the passkey registration
    - [x] Security considerations
    - [x] What should be done on the client side JS and server side verification for safety
        - [x] eg: Never store seed phrase except in memory
        - [x] Always validate that the end user has had a chance to download the seed phrase
        - [x] Make sure 3rd party js cannot access seed phrase
- [x] Spec on how to form and submit transactions aka the on-chain spec that the code will complete
    - [x] Inputs
    - [x] Hashes
    - [x] Signature data for verification
    - [x] P256 Proxy should sign:
       - [x] Tx Params
           - [x] Proxy Auth signature
           - [x] Parent/root Account Id
           - [x] Call
       - [x] Nonce
       - [x] Mortality?
- [x] The new Signed Extension(s) and what they will do
    - [x] `CheckNonce` (Should use the nonce of the parent/root account)
    - [x] `ChargeAssetTxPayment` or `ChargeTransactionPayment` (Should use the balance of the parent/root account)
    - [x] Add / Remove from other Signed Extension lists around Capacity/Free Tx or filters
- [x] Example code for how to use this from a backend
- [x] Example code for how to use this from a frontend
- [x] Options if needed for discussion by the team
    - [x] Unsigned Extensions vs MultiSignature and wrapping Signed Extensions

## Maybes

- [x] Should we make this more generic and allow use of keys from wallets not just generated keys?
- [x] Should we make MultiSignature support P256?
    - [x] Should we allow for P256 Accounts to hold tokens?
    - [x] Should we allow for P256 Accounts be MSA control keys? (Yes, but perhaps not now?)
- [x] Should we make a separate pallet for this?
    - [x] If so, can all the needed signed extensions also be in this pallet?

**Comment by aramikm** [comment]
![Passkey-Passkey Registration](https://github.com/frequency-chain/frequency/assets/9152501/ed5a568b-72ec-489d-a836-89c64a145510)
![Passkey-Passkey Transaction](https://github.com/frequency-chain/frequency/assets/9152501/7df6f3f7-6d6f-465a-a108-4ddf5335ce9a)
