### ISSUE TITLE
Implement migration for Pre-image for v1.2.0

### ISSUE THREAD

**Issue by enddynayn** [frequency-chain/frequency#2015]
**Description**
As part of the upgrade to v1.2.0, a lazy migration needs to be implemented. This is necessary because Pre-image now uses Considerations and no longer holds deposits directly.

Alternative: Remove all preimages.

**Acceptance Criteria:**
- [x] Run lazy migration script for Mainnet
- [x] Run lazy migration script for Testnet on Paseo 

https://github.com/paritytech/polkadot-sdk/pull/1363

**Comment by wilwade** [comment]
Completed.
