### ISSUE TITLE
[Bug]: Exported method SchemasRuntimeApi_get_schema_by_id is not found

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2054]
### What happened?

The runtime call for getting a schema by id is failing in Polkadotjs/app:

<img width="1739" alt="image" src="https://github.com/frequency-chain/frequency/assets/1252199/e409857e-b927-4439-aa3f-0e211ec5cd27">

Note that the Custom RPC for this still works, which is odd as it should be using that same RuntimeAPI.

### Relevant log output

```shell
schemasRuntimeApi.getSchemaById: Option<SchemaResponse>
-32000: Client error: Execution failed: Other: Exported method SchemasRuntimeApi_get_schema_by_id is not found
```

**Comment by aramikm** [comment]
Might be an issue with versioning?
