### ISSUE TITLE
Boosting: Update Pallet Readme Documentation

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2090]
Verify that the human readable documentation is updated with the extrinsics, state queries, and RPCs as needed.

- https://github.com/frequency-chain/frequency/blob/main/pallets/capacity/README.md

**Comment by shannonwells** [comment]
Up to date in the ProviderBoost branch: https://github.com/frequency-chain/frequency/pull/1694/files#diff-e505645c23b7d2fd2b3eeac7f66351cb2fae4dcb38363a40d8526c7c49108597
