### ISSUE TITLE
Signature Verification: Support Unwrapped Signatures in addtion to <Bytes> Wrapped

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2134]
## Summary

The [account_ownership_proof](https://github.com/frequency-chain/frequency/blob/9ef58185f2230aaf92dc166fb8eade56a78e4cf3/pallets/passkey/src/types.rs#L66) parameter in `PasskeyCall` signifies the signature of `<Bytes>PASSKEY_PUBLIC_KEY</Bytes>`. This means that the wallet client or browser must use this format during registration.

## Issue details

Currently, the polkadot-js-extension wraps all raw signed bytes inside the [<Bytes\>](https://github.com/polkadot-js/extension/pull/743) tag, and the Frequency protocol follows the same approach during passkey registration. Specifically, it signs the payload `<Bytes>PASSKEY_PUBLIC_KEY</Bytes>` using the private key of the user's Substrate Account. During the transaction process, it [wraps](https://github.com/frequency-chain/frequency/blob/9ef58185f2230aaf92dc166fb8eade56a78e4cf3/pallets/passkey/src/lib.rs#L318) the `passkey_public_key` inside `<Bytes>`.

However, since any entity can develop an infrastructure for passkey registration and transaction submission, there is a risk that others might not wrap the `PASSKEY_PUBLIC_KEY` in `<Bytes>`, potentially causing confusion.

## Risk

The current method could lead to interoperability issues if different implementations do not use the `<Bytes>` wrapping for the `PASSKEY_PUBLIC_KEY`. This inconsistency could result in failed signature verification and transaction errors.

## Mitigation

The [check_account_signature](https://github.com/frequency-chain/frequency/blob/9ef58185f2230aaf92dc166fb8eade56a78e4cf3/pallets/passkey/src/lib.rs#L312) function should verify signatures for both the raw `signed_data` and `<Bytes>signed_data</Bytes>`. This dual-check approach, as implemented in [pallet-nfts](https://github.com/paritytech/polkadot-sdk/blob/ebcbca3ff606b22b5eb81bcbfaa9309752d64dde/substrate/frame/nfts/src/common_functions.rs#L41), would ensure compatibility across different implementations and reduce the risk of verification failures.

## Suggestion

This should be fixed everywhere

- [x] Fix for passkey
- [x] Fix for handles
- [x] Fix for MSA Pallet: Delegation, Add Key, etc...
- [x] Fix for Stateful Storage: Signature Requried

**Comment by aramikm** [comment]
What is the benefit of applying this outside passkeys? Isn't applying this everywhere going to weaken the following claim?

> As a convention the polkadot-js-extension always wraps raw data in <Byte> tags to prevent
> malicious apps from tricking users into signing unintended transactions.
