### ISSUE TITLE
[Bug]: Provider can stake themselves out of a balance.

### ISSUE THREAD

**Issue by shannonwells** [frequency-chain/frequency#2167]
### What happened?

I reported this [same bug in Provider Dashboard](https://github.com/frequency-chain/provider-dashboard/issues/177) because I think there are bugs on both sides.

### Steps to reproduce
1. Connect to Provider Dashboard using an account that has <2 XRQCY.  In my case the account had about 1.4 XRQCY
1. Click "Become a Provider", sign transaction
1. Stake to Provider with the currently connected account
1. Balance is zero:
```shell
{
  free: 0
  reserved: 0
  frozen: 0
  flags: 170,141,183,460,469,231,731,687,303,715,884,105,728
}
```
I could logout and reconnect in Provider Dashboard, and the values still don't show correctly.
<img width="1481" alt="Screenshot 2024-09-26 at 3 47 06 PM" src="https://github.com/user-attachments/assets/51a63ca4-bbc6-4220-981c-9ba868dc4dd8">
<img width="1475" alt="Screenshot 2024-09-26 at 3 46 51 PM" src="https://github.com/user-attachments/assets/ec5932d1-d162-47bc-941e-502bbc09ffec">

**Comment by wilwade** [comment]
Might have been fixed on testnet, but unsure. Please retest now that Runtime v116 is live.

**Comment by shannonwells** [comment]
I am not reproducing it now.  I'll close it.
