### ISSUE TITLE
Support Address20 in Balance Transfer and Passkey Proxy

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2192]
To increase the support for different keys and wallets, we want to increase the support for ethereum style H160 accounts.

## AC

- [x] I should be able to send to an Ethereum style Address20 account using balances pallet
- [x] I should be able to use an `secp256k1` signature to send money from one Address20 account to any other account using balances pallet
- [x] I should be able to have a `Address20` address root to use with the Passkey Pallet
- [x] I should be able to use an secp256k1 signature to prove passkey authorization for any Passkey Pallet call that has an Address20 account root 
    - `PasskeyCall` account_id should allow for Address20
    - `PasskeyCall` account_ownership_proof should allow for secp256k1

**Comment by aramikm** [comment]
> I should be able to send to an Ethereum style Address20 account using balances pallet
Errors out with `CannotLookup`. The issue appears to be related to `AccountIdLookup` set in frame_system config.
```Rust
impl frame_system::Config for Runtime {
        ...
	type Lookup = AccountIdLookup<AccountId, ()>;
        ...
```

If we take a deeper look we see the following [code](https://github.com/paritytech/polkadot-sdk/blob/769bdd3ff33a291cbc70a800a3830638467e42a2/substrate/primitives/runtime/src/traits.rs#L260-L264) which only allows looking up By Id. We need to have a different implementation to make this work.
```Rust
	fn lookup(x: Self::Source) -> Result<Self::Target, LookupError> {
		match x {
			crate::MultiAddress::Id(i) => Ok(i),
			_ => Err(LookupError),
		}
	}
```

**Comment by aramikm** [comment]
Closed by https://github.com/frequency-chain/frequency/pull/2216
