### ISSUE TITLE
Discussion: Custom RPC Removal?

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2240]
Custom RPCs are discouraged due to the need to have augmented knowledge and the node based structure of it.

1. Currently many of our Custom RPCs are just mapped into the Runtime API.
2. Runtime APIs with correctly managed versions, do not have issues of data changes
3. Original reasons for Custom RPCs were:
    1. They could remain working and consistent even if the underlying APIs change. Runtime API versioning can fixes this.
    2. Rust instead of WASM for calculation
    3. Better APIs and responses (think non-SCALE parameters & responses). Fixed by Gateway project type work
    4. Off-chain indexing. No way around this one?

Question: Can we remove (deprecate) all or most Custom RPCs?

**Comment by aramikm** [comment]
Here is the list that I don't think we can remove:

- frequency_getMissingNonceValues
- msa_getKeysByMsaId

**Comment by JoeCap08055** [comment]
Removing existing RPCs would have to be a coordinated effort, as it would require changes in all of our deployed apps (Frequency Access, Gateway, Provider Boosting/Dashboard, Community Rewards, etc), as well as any Provider apps in production (MeWe).

Probably best to mark as deprecated for now and give the ecosystem time to adjust.

However, I think we should take a decision to not add any new RPCs going forward, unless there's no way around it (as for @aramikm 's list above)

**Comment by JoeCap08055** [comment]
Just a note: I confirmed that calling runtime APIs directly requires both _encoding_ and _decoding_ SCALE.

## Example: `get_handle_for_msa`

### RPC call
Input:
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "handles_getHandleForMsa",
    "params": [
        1111
    ]
}
```
Output:
```json
{
    "jsonrpc": "2.0",
    "result": {
        "base_handle": "nicolleveron",
        "canonical_base": "n1c011ever0n",
        "suffix": 52
    },
    "id": 1
}
```

### Runtime call
Input:
```json
{
    "jsonrpc": "2.0",
    "method": "state_call",
    "params": [
        "HandlesRuntimeApi_get_handle_for_msa",
        "0x5704000000000000" // SCALE-encoded representation of u64 1111
    ],
    "id": 1
}
```
Output:
```json
{
    "jsonrpc": "2.0",
    "result": "0x01306e69636f6c6c657665726f6e306e316330313165766572306e3400",
    "id": 1
}
```

**Comment by wilwade** [comment]
## Notes from Community Call 2024-12-19

- Could we check to see what is used in Gateway and move away from them in Gateway
- New JSON rpc interfaces from Substrate coming eventually
- Should not remove, but also not add new ones
- What about moving into the Ethereum interface
    - Abstraction layers help with this

General Agreement that:
- New Custom RPCs should be on a specific need only
- Leave existing Custom RPCs for now
- Suggest Gateway start to move away from using custom RPCs, where possible, so that Gateway is less dependent on node version
