### ISSUE TITLE
Look for places to add more debug logs in our custom pallets

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#521]
Goals:
- Make debugging easier
- Make developing on top of Frequency easier

**Comment by shannonwells** [comment]
Since this is marked "good first issue" this could use some boundaries

**Comment by rlaferla** [comment]
The recommended way of logging (used throughout Substrate) is frame_support::log.  See https://docs.substrate.io/test/debug

**Comment by wilwade** [comment]
Closing for now
